CREATE DATABASE BANK;
USE BANK;
CREATE TABLE Customer (
Customer_id INT PRIMARY KEY,
NAME VARCHAR(20),
CONTACT_NUMBER INT(20),
DOB VARCHAR(20),
ADDRESS VARCHAR(20));
 
CREATE TABLE LOAN(
Loan_Id INT PRIMARY KEY,
AMOUNT INT,
BORROWER INT);
 
CREATE TABLE PAYMENT(
PAYMENT_NO INT PRIMARY KEY,
PAYMENT_DATE DATE,
AMOUNT INT,
LOAN_ID INT,
FOREIGN KEY (LOAN_ID) REFERENCES LOAN(Loan_Id));
 
CREATE TABLE EMPLOYEE(
EMPLOYEE_ID INT PRIMARY KEY,
NAME VARCHAR(20),
CONTACT_NUMBER INT,
YEARS_OF_SERVICE INT,
BRANCH VARCHAR(20));
 
 
CREATE TABLE BRANCH(
BRANCH_NAME VARCHAR(20),
BANKER VARCHAR(20));

INSERT INTO Customer VALUES
(1, 'John Doe', 1234567, '1990-01-01', '123 Main St'),
(2, 'Jane Smith', 9876543, '1995-05-15', '456 Elm St'),
(3, 'Michael Johnson', 55519, '1988-12-10', '789 Oak St'),
(4, 'Emily Brown', 99988, '1982-03-20', '321 Pine St'),
(5, 'David Wilson', 11122, '1976-07-25', '567 Maple St');

INSERT INTO LOAN VALUES
(1, 5000, 1),
(2, 8000, 2),
(3, 10000, 3),
(4, 3000, 4),
(5, 12000, 5);

INSERT INTO PAYMENT VALUES
(1, '2024-01-15', 1000, 1),
(2, '2024-02-15', 1500, 2),
(3, '2024-03-15', 2000, 3),
(4, '2024-04-15', 500, 4),
(5, '2024-05-15', 1800, 5);

INSERT INTO EMPLOYEE VALUES
(1, 'Alice Johnson', 123459, 5, 'Branch A'),
(2, 'Bob Smith', 987654, 3, 'Branch B'),
(3, 'Charlie Brown', 55512, 8, 'Branch C'),
(4, 'Diana Wilson', 9998, 2, 'Branch D'),
(5, 'Eve Davis', 11122, 10, 'Branch E');

INSERT INTO BRANCH VALUES
('Goregaon','Priyanshu'),
('Goregon','Shlok'),
('Atlanta','George'),
('NYC','Vedant'),
('NYC','Ranapratap');

SELECT * FROM Customer;

SELECT NAME, ADDRESS FROM Customer;

SELECT SUM(AMOUNT) AS Total_Loans FROM LOAN;

SELECT c.NAME 
FROM Customer c 
JOIN LOAN l ON c.Customer_id = l.BORROWER;

SELECT COUNT(*) AS Total_Payments FROM PAYMENT;

SELECT NAME FROM EMPLOYEE;

SELECT * FROM LOAN WHERE AMOUNT > 5000;

SELECT * FROM Customer ORDER BY DOB ASC LIMIT 1;

SELECT BRANCH, COUNT(*) AS Employee_Count 
FROM EMPLOYEE 
GROUP BY BRANCH 
ORDER BY Employee_Count DESC 
LIMIT 1;

SELECT * 
FROM PAYMENT 
WHERE MONTH(PAYMENT_DATE) = 1 AND YEAR(PAYMENT_DATE) = 2024;

SELECT * FROM EMPLOYEE ORDER BY YEARS_OF_SERVICE DESC LIMIT 1;

SELECT DISTINCT l.* 
FROM LOAN l 
JOIN PAYMENT p ON l.Loan_Id = p.LOAN_ID;

SELECT c.* 
FROM Customer c 
LEFT JOIN PAYMENT p ON c.Customer_id = p.LOAN_ID 
WHERE p.LOAN_ID IS NULL;

SELECT * 
FROM PAYMENT 
WHERE PAYMENT_DATE > '2024-04-01';

SELECT COUNT(*) AS Total_Customers FROM Customer;

SELECT BRANCH_NAME, BANKER 
FROM BRANCH 
WHERE BRANCH_NAME = 'NYC';

SELECT l.Loan_Id, c.NAME
FROM LOAN l
JOIN Customer c ON l.BORROWER = c.Customer_id;

SELECT SUM(AMOUNT) AS Total_Payments_Made FROM PAYMENT;

SELECT NAME
FROM EMPLOYEE
WHERE CONTACT_NUMBER LIKE '%555%';

SELECT * FROM LOAN WHERE AMOUNT <= 3000;



SELECT BRANCH, COUNT(*) AS Employee_Count 
FROM EMPLOYEE 
GROUP BY BRANCH 
ORDER BY Employee_Count ASC 
LIMIT 1;



